# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
  namespace: default
spec:
  rules:
    - host: tickets.com
      http:
        paths:
          - path: /api/user/currentuser
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 4000
          - path: /api/user/signup
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 4000
          - path: /api/user/signout
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 4000
          - path: /api/user/signin
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 4000
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
#/api/comment/addComment/?(*) the star is regular expression, and can be anything
#in our case it will be the Postid
